/**
 * NovaTune — Indian Music Seed Script
 *
 * Seedes: 4 artist accounts, 12 songs, 4 albums
 * Run: node seed.js
 */

require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const fs = require('fs');
const path = require('path');
const { ImageKit } = require('@imagekit/nodejs');

const userModel  = require('./src/models/user.model');
const musicModel = require('./src/models/music.model');
const albumModel = require('./src/models/album.model');

// ── ImageKit ─────────────────────────────────────────────────────────────────
const imagekit = new ImageKit({
    urlEndpoint:  process.env.IMAGEKIT_URL_ENDPOINT,
    publicKey:    process.env.IMAGEKIT_PUBLIC_KEY,
    privateKey:   process.env.IMAGEKIT_PRIVATE_KEY,
});

async function uploadCover(filePath, filename) {
    const buffer = fs.readFileSync(filePath);
    const result = await imagekit.files.upload({
        file: buffer.toString('base64'),
        fileName: filename,
        folder: '/covers',
    });
    return result.url;
}

// ── Free sample audio from SoundHelix (royalty-free instrumentals) ───────────
// These are real, playable MP3 files used for demo purposes
const AUDIO = [
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
];

// ── Cover image paths (generated by Antigravity) ──────────────────────────────
const COVERS_DIR = path.join(__dirname, 'seed-covers');

async function seed() {
    console.log('\n🌱  NovaTune Seed Script\n');

    // ── Connect ──────────────────────────────────────────────────────────────
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅  MongoDB connected');

    // ── Upload covers to ImageKit ─────────────────────────────────────────────
    console.log('\n📸  Uploading cover images to ImageKit…');
    const covers = {};
    const coverFiles = {
        arijit:  'cover_arijit.jpg',
        rahman:  'cover_ar_rahman.jpg',
        shreya:  'cover_shreya.jpg',
        kishore: 'cover_kishore.jpg',
    };

    for (const [key, file] of Object.entries(coverFiles)) {
        const fp = path.join(COVERS_DIR, file);
        if (!fs.existsSync(fp)) {
            console.warn(`  ⚠️  ${file} not found — skipping cover upload for ${key}`);
            covers[key] = null;
        } else {
            covers[key] = await uploadCover(fp, file);
            console.log(`  ✅  ${key}: ${covers[key]}`);
        }
    }

    // ── Artists ───────────────────────────────────────────────────────────────
    console.log('\n👤  Creating artist accounts…');
    const PASSWORD = await bcrypt.hash('Artist@123', 10);

    const artistDefs = [
        { username: 'Arijit Singh',    email: 'arijit@novatune.com',  role: 'artist' },
        { username: 'A.R. Rahman',     email: 'rahman@novatune.com',  role: 'artist' },
        { username: 'Shreya Ghoshal',  email: 'shreya@novatune.com',  role: 'artist' },
        { username: 'Kishore Kumar',   email: 'kishore@novatune.com', role: 'artist' },
    ];

    const artists = {};
    for (const def of artistDefs) {
        let artist = await userModel.findOne({ email: def.email });
        if (!artist) {
            artist = await userModel.create({ ...def, password: PASSWORD });
            console.log(`  ✅  Created: ${def.username}`);
        } else {
            console.log(`  ♻️  Exists:  ${def.username}`);
        }
        artists[def.email] = artist;
    }

    const arijit  = artists['arijit@novatune.com'];
    const rahman  = artists['rahman@novatune.com'];
    const shreya  = artists['shreya@novatune.com'];
    const kishore = artists['kishore@novatune.com'];

    // ── Songs ─────────────────────────────────────────────────────────────────
    console.log('\n🎵  Creating songs…');

    const songDefs = [
        // Arijit Singh
        { title: 'Tum Hi Ho',        artist: arijit,  uri: AUDIO[0],  imageUrl: covers.arijit },
        { title: 'Channa Mereya',    artist: arijit,  uri: AUDIO[1],  imageUrl: covers.arijit },
        { title: 'Raabta',           artist: arijit,  uri: AUDIO[2],  imageUrl: covers.arijit },
        { title: 'Ae Dil Hai Mushkil', artist: arijit, uri: AUDIO[3], imageUrl: covers.arijit },

        // A.R. Rahman
        { title: 'Jai Ho',           artist: rahman,  uri: AUDIO[4],  imageUrl: covers.rahman },
        { title: 'Dil Se Re',        artist: rahman,  uri: AUDIO[5],  imageUrl: covers.rahman },
        { title: 'Roja',             artist: rahman,  uri: AUDIO[6],  imageUrl: covers.rahman },

        // Shreya Ghoshal
        { title: 'Lag Ja Gale',      artist: shreya,  uri: AUDIO[7],  imageUrl: covers.shreya },
        { title: 'Teri Meri',        artist: shreya,  uri: AUDIO[8],  imageUrl: covers.shreya },
        { title: 'Sunn Raha Hai',    artist: shreya,  uri: AUDIO[9],  imageUrl: covers.shreya },

        // Kishore Kumar
        { title: 'Mere Mehboob',     artist: kishore, uri: AUDIO[10], imageUrl: covers.kishore },
        { title: 'Roop Tera Mastana', artist: kishore, uri: AUDIO[11], imageUrl: covers.kishore },
    ];

    const songs = {};
    for (const def of songDefs) {
        let song = await musicModel.findOne({ title: def.title, artist: def.artist._id });
        if (!song) {
            song = await musicModel.create({
                title: def.title,
                artist: def.artist._id,
                uri: def.uri,
                imageUrl: def.imageUrl,
            });
            console.log(`  ✅  ${def.title} — ${def.artist.username}`);
        } else {
            console.log(`  ♻️  Exists: ${def.title}`);
        }
        songs[def.title] = song;
    }

    // ── Albums ────────────────────────────────────────────────────────────────
    console.log('\n💿  Creating albums…');

    const albumDefs = [
        {
            title: 'Aashiqui 2',
            artist: arijit,
            imageUrl: covers.arijit,
            musicTitles: ['Tum Hi Ho', 'Channa Mereya', 'Raabta', 'Ae Dil Hai Mushkil'],
        },
        {
            title: 'Vande Mataram',
            artist: rahman,
            imageUrl: covers.rahman,
            musicTitles: ['Jai Ho', 'Dil Se Re', 'Roja'],
        },
        {
            title: 'Timeless Melodies',
            artist: shreya,
            imageUrl: covers.shreya,
            musicTitles: ['Lag Ja Gale', 'Teri Meri', 'Sunn Raha Hai'],
        },
        {
            title: 'Golden Hits',
            artist: kishore,
            imageUrl: covers.kishore,
            musicTitles: ['Mere Mehboob', 'Roop Tera Mastana'],
        },
    ];

    for (const def of albumDefs) {
        let album = await albumModel.findOne({ title: def.title, artist: def.artist._id });
        if (!album) {
            const musicIds = def.musicTitles.map((t) => songs[t]?._id).filter(Boolean);
            album = await albumModel.create({
                title: def.title,
                artist: def.artist._id,
                imageUrl: def.imageUrl,
                music: musicIds,
            });
            console.log(`  ✅  "${def.title}" — ${musicIds.length} tracks`);
        } else {
            console.log(`  ♻️  Exists: ${def.title}`);
        }
    }

    console.log('\n🎉  Seed complete!\n');
    console.log('   Artist login credentials:');
    console.log('   ─────────────────────────────────────────');
    console.log('   Arijit Singh     arijit@novatune.com  | Artist@123');
    console.log('   A.R. Rahman      rahman@novatune.com  | Artist@123');
    console.log('   Shreya Ghoshal   shreya@novatune.com  | Artist@123');
    console.log('   Kishore Kumar    kishore@novatune.com | Artist@123');
    console.log('   ─────────────────────────────────────────\n');

    await mongoose.disconnect();
}

seed().catch((err) => {
    console.error('\n❌  Seed failed:', err.message);
    mongoose.disconnect();
    process.exit(1);
});
